# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js as the base image
FROM node:20-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Compile the TypeScript code
RUN npx tsc

# Use a slim Node.js image for the final build
FROM node:20-slim

# Set the working directory in the container
WORKDIR /app

# Copy compiled code from the builder stage
COPY --from=builder /app/dist ./dist

# Install only production dependencies
COPY package.json package-lock.json ./
RUN npm install --omit=dev

# Expose any necessary ports (assuming 3000 as an example)
EXPOSE 3000

# Command to run the application
CMD ["node", "dist/index.js"]
